name: flutter_anime_flix
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  http: ^0.13.5
  flutter_native_splash: ^2.0.4
  wave: ^0.2.2
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.1
  get_it: ^7.6.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  url_launcher: ^6.1.11
  path_drawing: ^1.0.1
  shimmer: ^3.0.0
  youtube_player_flutter: ^8.1.2
  flutter_launcher_icons: ^0.12.0
  flutter_rating_bar: ^4.0.1
  video_player: ^2.6.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/m.png"
  adaptive_icon_background: "#000000"

flutter_native_splash:
  android: true
  ios: true
  color: "#000000"
  image: "assets/images/m.png"



flutter:

  uses-material-design: true

  # assets:
  #   - assets/images/

  
  # fonts:
  #   - family: poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 900
