name: flutter_anime_flix
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  http: ^0.13.5
  flutter_native_splash: ^2.0.4
  wave: ^0.2.2
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.1
  get_it: ^7.6.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  url_launcher: ^6.1.11
  path_drawing: ^1.0.1
  shimmer: ^3.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#EEEEEE"
  image: "assets/images/salam.png"
  color_dark: "#EEEEEE"
  image_dark: assets/images/salam.png
  # branding_dark: assets/images/dark_spalsh.png
  android_gravity: center
  android_12:
    image: "assets/images/salam.png"
    icon_background_color: "#2F2E33"
    image_dark: assets/images/salam.png
    icon_background_color_dark: "#2F2E33"

  web: false



flutter:

  uses-material-design: true

  # assets:
  #   - assets/images/

  
  # fonts:
  #   - family: poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 900
